import { faker } from "@faker-js/faker";

export async function getTasks(): Promise<Array<Task>> {
  return faker.helpers.multiple(
    () => ({
      id: faker.string.uuid(),
      taskName: faker.helpers.arrayElement([
        "Development",
        "Meeting",
        "Support",
        "Deployment",
        "Testing",
        "Request Form",
        "Documentation",
        "Bug Fixed",
        "Discussion",
      ]),
      remark: faker.lorem.sentence(5),
      status: faker.helpers.arrayElement([
        "planned",
        "in-progress",
        "pending",
        "completed",
        "blocked",
      ]),
      complexity: faker.helpers.arrayElement(["Low", "Medium", "High"]),
      createdAt: faker.date.past(),
      fromTime: faker.date.soon(),
      toTime: faker.date.recent(),
      projectName: faker.helpers.arrayElement([
        "API Ring",
        "SSBP",
        "Digital Onbo",
        "CMS / TMS",
        "Documentation",
        "BA",
        "QMS",
        "CDMS",
        "SmartPay",
        "H2H",
        "SMS",
        "DocumentAI",
        "KBZPay",
        "Inbound Remittance",
        "N / A",
        "Credit - Card",
        "MiniApp",
        "PayAdvance",
        "Supply Chain",
        "ADBankAdmin",
      ]),
      projectManagerName: faker.person.fullName(),
      businessAnalystName: faker.person.fullName(),
      staffId: faker.number
        .int({
          min: 10000,
          max: 30000,
        })
        .toString(),
      staffName: faker.person.fullName(),
      category: faker.lorem.word(),
      departmentName: faker.helpers.arrayElement([
        "F01-HUMAN RESOURCE FUNCTION",
        "F03-SHARED SERVICE FUNCTION",
        "F04-LEGAL AND COMPLIANCE FUNCTION",
        "F05-INTERNAL AUDIT FUNCTION",
        "F06-TECHNOLOGY FUNCTION",
        "F07-MARKETING FUNCTION",
        "F08-CORPORATE AFFAIR FUNCTION",
        "F09-FINANCE FUNCTION",
        "F10-RISK MANAGEMENT FUNCTION",
        "F11-CREDIT FUNCTION",
        "F12-CEO OFFICE",
        "F13-CHAIRMAN OFFICE",
        "F14-Sale Function",
        "F15-OPERATION FUNCTION",
        "F16-DIGITAL PROFESSIONAL SERVICES",
        "F17-ANALYTICS CENTRE OF EXCELLENCE FUNCTION",
        "F18-KBZPay PMO FUNCTION",
        "F19-PUBLIC POLICY AND GOVERNMENT AFFAIRS",
        "F20-KBZPay CENTER OPERATION FUNCTION",
        "F21-SOFTWARE AND DATA ANALYTICS FUNCTION",
        "F22-MARKETING COMMUNICATIONS FUNCTION",
        "F23-MD OFFICE 1",
        "F24-MD OFFICE 2",
        "F25-KBZPAY OPERATIONS FUNCTION",
        "F26-VIRTUAL BRANCH FUNCTION",
        "F27-CASH MANAGEMENT FUNCTION",
        "F28-CAR (ALL COLLECTIONS AND RECOVERY) FUNCTION",
        "F29-BRANCH OPERATIONS, YGN AND LOWER MYANMAR",
        "F30-BRANCH OPERATIONS, MDY AND UPPER MYANMAR",
        "F31-BRANCH OPERATIONS, SHAN AND KAYAH",
        "F32-BRANCH OPERATIONS, NAY PYI TAW",
        "F33-CREDIT FUNCTION",
        "F34-ADMINISTRATION AND DIGITAL PROFESSIONAL SERVICES",
        "F35-GOVERNMENT AFFAIRS",
        "F36-KBZPAY BUSINESS INSIGHTS/ DATA",
        "F37-KBZPAY TREASURY AND PERFORMANCE MANAGEMENT",
        "V01-SMART CORPORATE / FI VC",
        "V02-SMART DEPOSIT / WEALTH VC",
        "V03-SMART SME VC",
        "V04-UNSECURED CONSUMER",
        "V05-SMART TERRITORIES - KAMARYUT VC",
        "V06-SMART COMMERCIAL REAL ESTATE VC",
        "V07-SMART VIRTUAL BRANCH VC",
        "V08-TRADE FINANCE",
        "V09-PAYROLL",
        "V10-SMART TRANSACTION BANKING VC",
        "V11-SMART TERRITORIES - BIG 28 VC",
        "V12-SMART SECURED CONSUMER VC",
        "V13-TREASURY",
        "V14-SMART CASH AND NETWORK LOGISTICS VC",
        "V15-CAR (ALL COLLECTIONS AND RECOVERY) VC",
        "V16-SMART TERRITORIES - EMERGING 600 VC",
        "V17-SMART DOMESTIC REMITTANCE VC",
        "V19-AGENT BANKING",
        "V20-SMART TERRITORIES (BLUE) VC",
        "V21-SMART TERRITORIES (RED) VC",
        "V22-SMART TERRITORIES (GREEN) VC",
        "V23-SMART INTERNATIONAL CORPORATE/ FI VC",
        "V24-LOCAL CORPORATE",
        "V25-WHOLESALE BANKING",
        "V26-STRUCTURED FINANCE",
        "V27-PROPERTY VC",
        "V28-BANCASSURANCE VC",
        "V29-SMART TERRITORIES 1 VC",
        "V30-SMART TERRITORIES 2 VC",
        "V31-SMART TERRITORIES 3 VC",
        "V32-SMART TERRITORIES 4 VC",
        "V33-SMART TERRITORIES 5 VC",
        "V34-DIGITAL HEALTH",
        "V35-KBZPAY MARKET",
        "V36-KBZPAY OFFICIAL ACCOUNTS AND CHAT",
        "V37-KBZPay Center",
        "V38-SMART CORPORATE TRANSACTION BANKING VC",
        "V39-Smart Retail Transaction Banking VC",
        "V40-OREO (OTHER REAL ESTATE OWNED)",
        "V41-SMART BUSINESS BANKING VC",
        "V42-SME AND BUSINESS BANKING",
        "V43-DEPOSIT/ WEALTH AND BANCASSURANCE VC",
        "V44-TRANSACTION BANKING",
        "V45-KBZPAY MINI APPS",
        "V46-DIGITAL PROFESSIONAL SERVICES",
        "V47-COMMERCIAL BANKING",
        "V48-INTERNATIONAL CORPORATE",
        "V49-INSTITUTIONAL BANKING",
        "V50-KBZPAY, DIGITAL BANKING AND CARD BUSINESS",
        "V51-MD OFFICE 3",
        "V52-MD OFFICE 4",
        "V53-MD OFFICE 5",
        "V54-CARD BUSINESS",
        "V55-MANAGED SERVICE BUSINESS",
        "V56-WEALTH AND BANCASSURANCE",
        "V57-CUSTOMER SERVICE",
        "V58-RETAIL BANKING",
        "V59-FINTECH",
        "V60-DEPOSIT",
        "V61-MORTGAGE",
        "V62-KBZPAY LENDING",
        "V63-SALES AND ENGAGEMENT",
        "V64-KBZPAY",
        "V65-KBZPAY EMERGING 6 MILLIONS",
        "V66-BANCASSURANCE",
        "V67-WEALTH",
        "N/A",
      ]),
      subTaskName: faker.helpers.arrayElement([
        "API",
        "New",
        "Production",
        "UAT",
        "VPN Request",
        "AD Request",
        "API Documentation",
        "Change Request",
        "Handover",
        "Portal",
        "Enhancement",
        "Daily Standup Meeting",
        "Interview",
        "Team Discussion",
      ]),
    }),
    { count: 10 }
  );
}
